name: rust-gh-action
description: "Test action to try developng GitHubActions in Rust"
inputs:
  dummy-input:
    description: "A dummy input"
    required: false
    default: ""
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.dummy-input }}
