name: rust-gh-action
description: "Test action to try developng GitHubActions in Rust"

inputs:
  url:
    description: "The URL to call"
    required: true
    default: "https://httpbin.org/get"

outputs:
  error:
    description: "Any error that may occur"
    value: ${{ steps.run-container.outputs.error }}
  response:
    description: "JSON response from calling the input URL"
    value: ${{ steps.run-container.outputs.response }}

runs:
  using: "composite"
  steps:
    - name: Cache docker layers
      uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
    - name: Build docker image
      run: docker build -t rust-gh-action .
      shell: bash
    - name: Run container
      id: run-container
      run: docker run -v $GITHUB_OUTPUT:/output rust-gh-action ${{ inputs.url }}
      shell: bash
