name: rust-gh-action
description: "Test action to try developng GitHubActions in Rust"
inputs:
  dummy-input:
    description: "A dummy input"
    required: true
    default: "blah"
runs:
  using: "composite"
  steps:
    - uses: satackey/action-docker-layer-caching@v0.0.11
      continue-on-error: true
    - name: Build docker image
      run: docker build -t rust-gh-action .
      shell: bash
    - name: Run action
      run: docker run rust-gh-action ${{ inputs.dummy-input }}
      shell: bash
