name: Test consuming this action
on:
  push

jobs:
  test_success:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        id: run-action
        with: 
          url: "https://httpbin.org/get"
      - run: echo "${{ steps.run-action.outputs.response }}"
