name: Test consuming this action
on:
  push

jobs:
  test_success:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run action
        uses: ./
        id: run-action
        with: 
          url: "https://httpbin.org/get"
      - name: Print output
        run: echo "${{ steps.run-action.outputs.response }}"
